### ISSUE TITLE
Lore of Bows

### ISSUE THREAD

**Issue by electronicboy** [BattlePlugins/BattleTracker#10]
Hello!

Thanks for supporting this plugin, and gives some interesting death messages, however!

The users of the server complain that the lore name of bows isn't shown inside the death messages, I was going to look into doing it but I'd need to to a bit of work to get it to compile on my machine as I don't have a lot of older stuff in my maven cache due to lots of re-installs and was wondering if this would be something you'd be willing to add?

Cheers!

**Comment by Europia79** [comment]
@electronicboy 

okay, i added this feature to v2.5.9.1

download:
http://dev.bukkit.org/bukkit-plugins/battletracker2/

Here's the code changes, if you wanna take a look:
https://github.com/BattlePlugins/BattleTracker/compare/c02c720ec021...db39c32cc16c

documentation:
As you can see in the code & commit messages, in order to display the lore, go into messages.yml and add %l <-- The symbol is a lowercase elle, which obviously stands for Lore.

**Comment by electronicboy** [comment]
Looking good, Cheers!
Can't wait to get it up and running on the server! :+1:
