### ISSUE TITLE
SkillAPI conflict

### ISSUE THREAD

**Issue by TheOneTwelfth** [BattlePlugins/BattleTracker#18]
When a player kills other player or a mob using SkillAPI skills, the exception is thrown and when the player is killed, the default kill message shows, instead of a custom one specified in config.
Here's the exception: http://pastebin.com/Ekkk95gk

**Comment by Zach443** [comment]
From what I can see, SkillsAPI is abandoned. If this becomes an issue again in the future we can open this back up.

**Comment by Europia79** [comment]
https://github.com/BattlePlugins/BattleTracker/blob/master/src/java/mc/alk/tracker/listeners/BTEntityListener.java#L187

None of the line numbers are matching up with MCCore.jar & SkillsAPI.jar so it makes it harder without know what versions he was using.

It looks like they have custom entities that listen for damage events which forwards it to the MCCore library which does damage, death, & hence the death event here & the null target object on line 187.

https://github.com/BattlePlugins/BattleTracker/blob/master/src/java/mc/alk/tracker/listeners/BTEntityListener.java#L67-L69

Which should never have been called for instanceof PlayerDeathEvent because it's handle by the listen directly above it.  The listener here is for when a Player kills a mob AND BattleTracker is set to track PvE.

That's just what I see at a quick glance without going too much into the SkillsAPI code.
