### ISSUE TITLE
add reset db command /bt resetall

### ISSUE THREAD

**Issue by helptiger** [BattlePlugins/BattleTracker#3]
Please add a command to reset all db entries.

**Comment by lDucks** [comment]
@Zach443 is this resolved?

**Comment by Zach443** [comment]
@lDucks This function has not been implemented into BattleTracker as of yet.

**Comment by Europia79** [comment]
I'm pretty sure users could just stop the server and delete their database file:

```
/plugins/BattleTracker/tracker.sqlite
```

Personally, i really like sqlite... but I think we should also support MySQL too, as well as other databases.

**Comment by Zach443** [comment]
Should be simple enough to add a command pointing to this.. 

https://github.com/BattlePlugins/BattleTracker/blob/master/src/java/mc/alk/tracker/serializers/SQLInstance.java#L563

**Comment by Zach443** [comment]
I just skimmed through the Executor class and found that there is actually already a command to do this, haha. 

You should be able to use `/bt resetRatings` in order to accomplish this task. Code [here](https://github.com/BattlePlugins/BattleTracker/blob/master/src/java/mc/alk/tracker/executors/BattleTrackerExecutor.java#L71), for documentation purposes.
